import groovy.json.*
args_map = [version:"1.$BUILD_NUMBER"]
print "Build number: "+BUILD_NUMBER
version = BUILD_NUMBER
print "version: "+version

pipeline {
  agent any
  stages {
    stage('checkout') {
      steps {
        echo 'Hello World'
        checkout([$class:'GitSCM', branches:[[name: '*/master']], extensions:[], userRemoteConfigs:[[url: 'https://github.com/vasyliev123/kelownaDeploymentOCI']]])
        sh 'echo `pwd`'
        sh 'ls -alrt'
      }
    }
  }
}