import groovy.json.*

def args_map = [version: "12"]
def version = "123"

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'tar -zcvf public.tar.gz public'
            }
        }

        stage('OCI Upload Artifact') {
            steps {
                script {
                    OCIUploadArtifact(
                        credentialsId: 'OCI-CREDS',
                        uploadArtifactDetailsList: [
                            [
                                artifactPath: 'public.tar.gz',
                                repositoryId: 'ocid1.artifactrepository.oc1.ca-montreal-1.0.amaaaaaabpz627qaxv5tx6zorink4he5qe7ejyrwixmpudgkkaxfqqmb2m4q',
                                repositoryType: 'GENERIC',
                                sourcePath: 'public.tar.gz',
                                version: "1.${BUILD_NUMBER}"
                            ],
                            [
                                artifactPath: 'deployment_spec.yaml',
                                repositoryId: 'ocid1.artifactrepository.oc1.ca-montreal-1.0.amaaaaaabpz627qaxv5tx6zorink4he5qe7ejyrwixmpudgkkaxfqqmb2m4q',
                                repositoryType: 'GENERIC',
                                sourcePath: 'deployment_spec.yaml',
                                version: "1.${BUILD_NUMBER}"
                            ]
                        ],
                        endpoint: 'https://devops.ca-montreal-1.oci.oraclecloud.com',
                        pollingConfig: [timeoutSeconds: 600, pollingIntervalSeconds: 5],
                        executionMode: 'SYNC'
                    )
                }
            }
        }

        stage('Trigger Deployment') {
            steps {
                script {
                    OCIDeployment(
                        argumentVal: JsonOutput.toJson(args_map),
                        credentialsId: 'OCI-CREDS',
                        displayName: "testDeployment",
                        endpoint: 'https://devops.ca-montreal-1.oci.oraclecloud.com',
                        pipelineId: 'ocid1.devopsdeploypipeline.oc1.ca-montreal-1.amaaaaaabpz627qa72vucdegbcvjgvy265vfregdcmp4cxkyogoyzzfp2ggq',
                        pollingConfig: [timeoutSeconds: 600, pollingIntervalSeconds: 5],
                        executionMode: 'SYNC'
                    )
                }
            }
        }
    }
}
